//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Project_MedicalTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int PatientID { get; set; }
        public int ParticularID { get; set; }
        public Nullable<int> Quntity { get; set; }
    
        public virtual Particular Particular { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
